# Generated by Django 5.0.3 on 2024-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Is_Lab',
        ),
        migrations.RemoveField(
            model_name='section',
            name='Section_Meet',
        ),
        migrations.AddField(
            model_name='section',
            name='Building_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Credits',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='End_Times',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Meets_Days',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Room_Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Section_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Section_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Start_Times',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
