# Generated by Django 5.0.3 on 2024-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Phone_Number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Home_Address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
