# Generated by Django 5.0.3 on 2024-04-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0002_user_user_phone_number_alter_user_user_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_FName',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Home_Address',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_LName',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Password',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Phone_Number',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
