# Generated by Django 5.0.3 on 2024-04-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0002_remove_section_is_lab_remove_section_section_meet_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assign_user_junction',
            unique_together=set(),
        ),
    ]
