# Generated by Django 5.0.4 on 2024-05-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0003_alter_assign_user_junction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Skill',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
