# Generated by Django 5.0.3 on 2024-04-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0004_alter_assign_user_junction_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_user_junction',
            name='Section_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ta_app.section'),
        ),
    ]
