# Generated by Django 5.0.4 on 2024-04-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0005_alter_assign_user_junction_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_ID',
            field=models.IntegerField(default=0),
        ),
    ]
